// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmsmdybthrxqbiprpozw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtc21keWJ0aHJ4cWJpcHJwb3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDU5ODgsImV4cCI6MjA3MzcyMTk4OH0.pkcp-MFN03iyawyyvkPryMisgNSI2NcgXWw-anCmpP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});